from app.schemas.learning_input import LearningInput


class MockAIProvider:
    def generate_topic_summary(
        self,
        topic_title: str,
        learning_inputs: list[LearningInput],
    ) -> str:
        if not learning_inputs:
            return (
                f"You have created the topic '{topic_title}', "
                "but you have not added any learning inputs yet."
            )

        input_count = len(learning_inputs)

        combined_preview = "\n".join(
            f"- {learning_input.content[:120]}"
            for learning_input in learning_inputs
        )

        return f"""
Here is a simple learning summary for "{topic_title}":

You have added {input_count} learning input(s) for this topic.

Based on your saved inputs, this topic currently seems to cover:

{combined_preview}

Simple takeaway:
This is an early AI-generated summary placeholder. Later, this section will be generated by a real AI provider like OpenAI, Claude, or a local Ollama model.

For now, the important thing is that the app flow works:
saved inputs → backend summary API → AI provider layer → topic summary.
""".strip()


def get_ai_provider():
    return MockAIProvider()