from fastapi import HTTPException

from app.core.config import settings


class MockAIProvider:
    def generate_topic_summary(
        self,
        topic_title: str,
        learning_inputs: list,
    ) -> str:
        if not learning_inputs:
            return (
                f"You have created the topic '{topic_title}', "
                "but you have not added any learning inputs yet."
            )

        input_count = len(learning_inputs)

        combined_preview = "\n".join(
            f"- {learning_input.content[:120]}"
            for learning_input in learning_inputs
        )

        return f"""
Here is a simple learning summary for "{topic_title}":

You have added {input_count} learning input(s) for this topic.

Based on your saved inputs, this topic currently seems to cover:

{combined_preview}

Simple takeaway:
This summary is currently generated by the mock AI provider. This is useful for development because it lets you test the app without spending money on real AI API calls.

Current AI provider:
{settings.AI_PROVIDER}

Later, this same provider layer can call OpenAI, Claude, or Ollama without changing the frontend.
""".strip()


class OpenAIProvider:
    def generate_topic_summary(self, topic_title: str, learning_inputs: list) -> str:
        raise HTTPException(
            status_code=501,
            detail="OpenAI provider is configured but not implemented yet.",
        )


class ClaudeProvider:
    def generate_topic_summary(self, topic_title: str, learning_inputs: list) -> str:
        raise HTTPException(
            status_code=501,
            detail="Claude provider is configured but not implemented yet.",
        )


class OllamaProvider:
    def generate_topic_summary(self, topic_title: str, learning_inputs: list) -> str:
        raise HTTPException(
            status_code=501,
            detail="Ollama provider is configured but not implemented yet.",
        )


def get_ai_provider():
    if settings.AI_PROVIDER == "mock":
        return MockAIProvider()

    if settings.AI_PROVIDER == "openai":
        return OpenAIProvider()

    if settings.AI_PROVIDER == "claude":
        return ClaudeProvider()

    if settings.AI_PROVIDER == "ollama":
        return OllamaProvider()

    raise HTTPException(
        status_code=400,
        detail=f"Unsupported AI provider: {settings.AI_PROVIDER}",
    )